const style = {
  container: {
    width: "99%",
    marginLeft: "auto",
    marginRight: "auto",
    textAlign: "center",
    "& p": {
      backgroundColor: "#eeeeee",
      borderRadius: "13px",
      padding: "30px",
    },
  },
  description: {
    marginLeft: "auto",
    marginRight: "auto",
    textAlign: "center",
    width: "80%",
    display: "flex",
    justifyContent: "space-evenly",
    alignItems: "center",
    marginTop: "100px",
    padding: "40px",
  },
  img: {
    maxWidth: "100%",
    maxHeight: "100%",
    width: "28%",
    margin: "2px",
    borderRadius: "50%",
    boxShadow: "rgba(0, 0, 0, 0.56) 0px 22px 70px 4px",
    border: "solid 0.3rem #b58162",
  },
  imgEntrance: {
    maxWidth: "100%",
    maxHeight: "100%",
    height: "auto",
    width: "30%",
    margin: "2px",
    borderRadius: "13px",
    boxShadow: "rgba(0, 0, 0, 0.56) 0px 22px 70px 4px",
  },
  imgCertificate: {
    maxWidth: "100%",
    maxHeight: "100%",
    height: "25em",
    width: "auto",
  },
  paragraphHistory: {
    width: "70%",
    marginRight: "40px",
    backgroundColor: "#eeeeee",
    boxShadow: "rgb(38, 57, 77) 0px 20px 30px -10px",
    fontFamily: "'Libre Baskerville', serif",
    fontSize: "1.5rem",
    paddingTop: "15px",
    textAlign: "left",
  },
  history: {
    display: "flex",
    justifyContent: "space-evenly",
    alignItems: "center",
    marginTop: "50px",
    marginBottom: "110px",
    "& p": {
      width: "33%",
      backgroundColor: "#eeeeee",
      boxShadow: "rgb(38, 57, 77) 0px 20px 30px -10px",
      fontFamily: "'Libre Baskerville', serif",
      fontSize: "1.5rem",
      paddingTop: "15px",
      textAlign: "left",
    },
  },
  society: {
    marginTop: "50px",
  },
};

export default style;
